### ISSUE TITLE
Should lizard folk (and possibly dragons?) drop scute when butchered?

### ISSUE THREAD

**Issue by Proxiehunter** [RobbieNeko/Magical-Nights#11]
After [this](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5466) Bright Nights update should lizard folk, dragons, and any other reptilian monsters I'm forgetting about give scute when butchered? For that matter should any other monsters added by this mod provide materials found in this update when butchered?

Apologies if I've failed to understand something and the monsters are already in categories that makes them already compatible with this update so they _already_ drop these things where appropriate.

**Comment by RobbieNeko** [comment]
Lizard folk don't make too much sense to have scutes, and dragons already drop scales. In general, I'd say the currently existing monsters that suit scutes already have modded materials.

I'll definitely make sure the mod is compatible though!

**Comment by RobbieNeko** [comment]
Made sure the mod isn't fucking up any of the harvest entries ^-^
