### ISSUE TITLE
Could this be compatible with DDA?

### ISSUE THREAD

**Issue by themaster567** [RobbieNeko/Magical-Nights#12]
Is it possible for this to function in DDA in any capacity, or does it rely on functions that exist in one codebase and not another.

Don't worry, I did read the sidebar. I'm more wondering "will this instantly detonate" and "how broken will this be".

I ask this because I really quite like all the changes you made, but I also like to play DDA from time to time, and I don't want to go back to the old version in their repo.

**Comment by RobbieNeko** [comment]
If you go far back enough in DDA there's a chance it'll work fine, but I fear any remotely modern DDA release will probably be very angry about it. After all, I'm sure there's all sorts of fields it expects me to specify, and I've got no real interest in working on a DDA version.

**Comment by themaster567** [comment]
Totally reasonable, thanks for the answer.
