### ISSUE TITLE
Everburning Torch != nearby fire

### ISSUE THREAD

**Issue by JinJanODWan** [RobbieNeko/Magical-Nights#6]
Thank you very much for Magical Nights; it's just what I needed. I found an issue and hope this is right place and way to report:

It seems the _everburning torch_ doesn't count as fire for some reason. It says it will in the extended inventory info but when crafting there's no _nearby fire_ in the list. It is in my inventory and it is lit. Chucking it on the floor or extinguishing it leads to same disappointing results.

![image](https://github.com/RobbieNeko/Magical-Nights/assets/44056502/29dd13a5-72f9-40c2-9d36-b2aa962ef380)
Extended Inventory Info

![image](https://github.com/RobbieNeko/Magical-Nights/assets/44056502/cbb3d82d-979a-425a-84e6-d86dbc896dea)
Crafting

I suspect it has something to do with the recent JSONifying of BN but have no idea what might be missing.

**Comment by RobbieNeko** [comment]
Hmm... it has the "Fire" flag, which is presumably what's giving it that text in the description. But at the same time, I get the distinct feeling that flag doesn't actually work properly.

**Comment by JinJanODWan** [comment]
Yeah. It seems the problem lies in the flag's coding being broken. So I did some digging and found [this PR](https://github.com/CleverRaven/Cataclysm-DDA/pull/62129) on DDA.

I can confirm that changing
`"sub": "torch_lit"`
to
`"sub": "fire"`
in [enchanted_misc.json](https://github.com/RobbieNeko/Magical-Nights/blob/2be6422b19ec5d4143f2eb2437be70b6c55ab71a/Magical%20Nights/items/enchanted_misc.json#L96) gives expected results
![image](https://github.com/RobbieNeko/Magical-Nights/assets/44056502/ba0e67cf-fa56-4ac7-bb30-978decd4f566)
_Crafting with everburning torch_

It also still functions as it used to as far as I can tell.

They also mention "Pocket Sun" in the linked PR but I couldn't find it here. I also don't know how to make changes on here so sorry for not affecting changes myself.

**Comment by RobbieNeko** [comment]
Pocket sun is presumably something added to Magiclysm on down the line from when BN split off of DDA. But aye, looks like that'd be the solution

**Comment by RobbieNeko** [comment]
Fixed as demonstrated above in recent commit
