### ISSUE TITLE
Tainted Blood Overwrite

### ISSUE THREAD

**Issue by yay855** [RobbieNeko/Magical-Nights#8]
For whatever reason, Magical Nights's overwrite of Tainted Blood means that you can't do the 'analyze zombie blood' quest for the Refugee Center Doctor, the centrifuge console treats it like it isn't blood.

**Comment by RobbieNeko** [comment]
That's because it isn't the blood that the console is looking for.
Magical Nights zombie blood is tainted_blood, but vanilla BN zombie blood is blood_tainted

**Comment by RobbieNeko** [comment]
In any case, I'll work on it later don't worry. At least it's not *too* major of an issue

**Comment by Ignaramico** [comment]
i think that there is still a zombie that for whatever reason doesnt got the blood override, i think it was the zombie cop

**Comment by RobbieNeko** [comment]
Fixed in today's PR (hopefully!)
